kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: buildah-custom
  namespace: vindular-dev
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'buildah:latest'
  resources: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: .tekton/Dockerfile.buildah
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/vindulaR/openshift-sample.git'
  runPolicy: Serial
